[project]
name = "data_clean_utils"
version = "0.1.0"
description = "Utility functions for data cleaning and preprocessing"
authors = [
    { name = "GregoryD-Git" }
]
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }

dependencies = [
    "pandas",
    "numpy"
]

[project.urls]
Homepage = "https://github.com/GregoryD-Git/data_clean_funcs"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"